import './globals.css'
import Navbar from './components/Navbar'
import type { Metadata } from 'next'



export const metadata: Metadata = {
  title: "Kat's NextJS App",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-stone-700">
      <Navbar />
        {children}
      </body>
    </html>
  )
}
