import { Inter } from 'next/font/google'
import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })




export const metadata: Metadata = {
  title: "Home",
  description: 'Generated by create next app',
}
export default function Home() {
  return (
    <main className={inter.className}>
      <h1 className="text-3xl text-stone-50"> Hello World</h1>
    </main>
  )
}
